services:
  gniotek:
    container_name: gniotek
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      DB_PATH: /data/gniotek.db
      MIGRATIONS_PATH: file:///app/db/migrations
    volumes:
      - ./data:/data
    command: ["./gniotek"]
